import {StyleSheet} from "react-native";
import {globalStyles} from "./global.styles";

export const styles = StyleSheet.create({
    safe: globalStyles.screen,
    container: {
        padding: 16,
        paddingBottom: 32,
    },
    title: {
        ...globalStyles.title,
        backgroundColor: "#eee",
        paddingHorizontal: 24,
        paddingVertical: 8,
        paddingBottom: 12,
        borderRadius: 20,
        overflow: "hidden",
        position: "absolute",
        top: 52,
        alignSelf: "center",
        zIndex: 10,
    },
    card: globalStyles.card,
    sectionCard: globalStyles.sectionCard,
    controlsCard: globalStyles.sectionCard,
    statsCard: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
        marginBottom: 14,
    },
    statItem: globalStyles.statItem,
    statLabel: globalStyles.statLabel,
    statValue: globalStyles.statValue,
    sectionTitle: globalStyles.sectionTitle,
    mapTitle: {
        alignSelf: "center",
        textAlign: "center",
        fontSize: 24,
        fontWeight: "800",
        marginBottom: 10,
    },
    input: globalStyles.input,
    pickerWrap: globalStyles.pickerWrap,
    picker: globalStyles.picker,
    row: globalStyles.row,
    flex1: globalStyles.flex1,
    primaryButton: globalStyles.buttonPrimary,
    primaryButtonText: globalStyles.buttonPrimaryText,
    secondaryButton: globalStyles.buttonSecondary,
    secondaryButtonText: globalStyles.buttonSecondaryText,
    errorText: globalStyles.errorText,
    emptyText: globalStyles.emptyText,
    loadingWrapper: {paddingVertical: 24},
    topRightCard: {
        position: "absolute",
        top: 48,
        right: 48,
        width: "30%",
        zIndex: 1,
    },
    topLeftCard: {
        position: "absolute",
        top: 48,
        left: 48,
        width: "30%",
        zIndex: 1,
    },
});