import {StyleSheet} from "react-native";

export const globalStyles = StyleSheet.create({
    screen: {flex: 1, backgroundColor: "#f5f7fb"},
    card: {
        backgroundColor: "#fff",
        borderRadius: 20,
        padding: 14,
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: {width: 0, height: 4},
        elevation: 2,
    },
    sectionCard: {
        backgroundColor: "#f8f8f8",
        borderRadius: 20,
        padding: 14,
        marginBottom: 14,
        shadowColor: "#000",
        shadowOpacity: 0.06,
        shadowRadius: 10,
        shadowOffset: {width: 0, height: 4},
        elevation: 2,
    },
    cardCompact: {
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 16,
        padding: 14,
    },
    title: {
        fontSize: 36,
        fontWeight: "800",
        color: "#102a43",
        alignSelf: "center",
        marginBottom: 14,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "800",
        color: "#102a43",
        marginBottom: 10,
        textAlign: "center",
    },
    input: {
        borderWidth: 1,
        borderColor: "#d9e2ec",
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 11,
        backgroundColor: "#fff",
        marginBottom: 10,
    },
    pickerWrap: {
        borderWidth: 1,
        borderColor: "#d9e2ec",
        borderRadius: 14,
        overflow: "hidden",
        backgroundColor: "#fff",
        marginBottom: 10,
    },
    picker: {
        height: 50,
        width: "100%",
        color: "#102a43",
    },
    row: {flexDirection: "row", gap: 10},
    rowBetween: {flexDirection: "row", justifyContent: "space-between"},
    flex1: {flex: 1},
    buttonPrimary: {
        flex: 1,
        backgroundColor: "#1976d2",
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: "center",
    },
    buttonSecondary: {
        width: 100,
        backgroundColor: "#e9eef6",
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: "center",
    },
    buttonPrimaryText: {
        color: "#fff",
        fontWeight: "800",
    },
    buttonSecondaryText: {
        color: "#102a43",
        fontWeight: "700",
    },
    errorText: {
        color: "#b00020",
        fontWeight: "700",
        paddingVertical: 10,
    },
    emptyText: {
        color: "#627d98",
        paddingVertical: 10,
    },
    statItem: {
        width: "48%",
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 12,
    },
    statLabel: {color: "#627d98", fontSize: 12, marginBottom: 4},
    statValue: {color: "#102a43", fontSize: 16, fontWeight: "800"},
    centeredOverlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        zIndex: 2,
    },
    mutedOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(255,255,255,0.55)",
    },
});